/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Part1(props) {
  const { nodes, materials } = useGLTF("/assets/part1.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Ground002"
        geometry={nodes.Ground002.geometry}
        material={materials["Ground and road"]}
        position={[-148.03, 9.46, -32.88]}
        scale={15.09}
      />
      <mesh
        name="parking"
        geometry={nodes.parking.geometry}
        material={materials["newest parking"]}
        position={[-85.3, 9.48, -141.91]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[2.39, 0.15, 0.15]}
      />
      <mesh
        name="Gate_and_Lights001"
        geometry={nodes.Gate_and_Lights001.geometry}
        material={materials["Main Gate"]}
        position={[-106.4, 14.28, 73.87]}
        scale={15.09}
      />
    </group>
  );
}
