/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Part7(props) {
  const { nodes, materials } = useGLTF("/assets/part7.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Hall_005003"
        geometry={nodes.Hall_005003.geometry}
        material={materials.akshaya}
        position={[-190.85, 18.52, 135.93]}
        scale={9.48}
      />
      <mesh
        name="Hall_006002"
        geometry={nodes.Hall_006002.geometry}
        material={materials.jh}
        position={[-212.88, 31.85, 176.77]}
        scale={[15.09, 14.95, 15.09]}
      />
      <mesh
        name="Hall_010"
        geometry={nodes.Hall_010.geometry}
        material={materials.AH}
        position={[-194.53, 31.81, 348.59]}
        scale={[15.09, 14.95, 15.09]}
      />
      <mesh
        name="Hall_011"
        geometry={nodes.Hall_011.geometry}
        material={materials["As Ho"]}
        position={[-181.03, 31.87, 385.97]}
        scale={[15.09, 14.95, 15.09]}
      />
    </group>
  );
}
