/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF, Html } from "@react-three/drei";
import "../../App.scss";

export default function Part8(props) {
  const { nodes, materials } = useGLTF("/assets/part8.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Plane110"
        geometry={nodes.Plane110.geometry}
        material={materials.Base}
        position={[8.55, 11.38, -11.17]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[9.75, 13.86, 13.86]}
      />
      <mesh
        name="Text"
        geometry={nodes.Text.geometry}
        material={materials["Registration Desk"]}
        position={[-57.28, 11.96, -7.56]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={0.65}
      />
      <mesh
        name="Text001"
        geometry={nodes.Text001.geometry}
        material={materials["Registration Desk"]}
        position={[-92.6, 11.38, -26.69]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={1.02}
      />
      <mesh
        name="reg"
        geometry={nodes.reg.geometry}
        material={materials["Registration Table"]}
        position={[-58.94, 10.64, -8.27]}
        scale={[0.63, 0.33, 0.33]}
      />
      <mesh
        name="screen"
        geometry={nodes.screen.geometry}
        material={materials["Projector Screen"]}
        position={[-52.5, 12.3, -0.07]}
        rotation={[Math.PI / 2, 0, 1.57]}
        scale={[3.81, 3.81, 1.96]}
      >
        {/* <Html
          className="content1"
          rotation-x={-Math.PI / 2}
          position={[1, 0.02, 0]}
          transform
          occlude
        >
          <div className="wrapper">
            <iframe
              width="560"
              height="315"
              src="https://www.youtube.com/embed/SwNiSfZSel8?rel=0&autoplay=0&loop=1&modestbranding=1&fs=0"
              title="YouTube video player"
              frameBorder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
            ></iframe>
          </div>
        </Html> */}
      </mesh>
    </group>
  );
}
