/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Part2(props) {
  const { nodes, materials } = useGLTF("/assets/part2.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Trees001"
        geometry={nodes.Trees001.geometry}
        material={materials["New Tree"]}
        position={[-75.16, 12.88, -201.56]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees002"
        geometry={nodes.Trees002.geometry}
        material={materials["New Tree"]}
        position={[-69.36, 12.88, -197.74]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees003"
        geometry={nodes.Trees003.geometry}
        material={materials["New Tree"]}
        position={[-62.49, 12.88, -194.99]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees004"
        geometry={nodes.Trees004.geometry}
        material={materials["New Tree"]}
        position={[-60.42, 12.88, -187.13]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees005"
        geometry={nodes.Trees005.geometry}
        material={materials["New Tree"]}
        position={[-54.33, 12.88, -189]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees006"
        geometry={nodes.Trees006.geometry}
        material={materials["New Tree"]}
        position={[-49.66, 12.88, -181.08]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees007"
        geometry={nodes.Trees007.geometry}
        material={materials["New Tree"]}
        position={[-41.32, 12.88, -181.64]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees008"
        geometry={nodes.Trees008.geometry}
        material={materials["New Tree"]}
        position={[-40.73, 12.88, -173.73]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees009"
        geometry={nodes.Trees009.geometry}
        material={materials["New Tree"]}
        position={[-32.53, 12.88, -171.04]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees010"
        geometry={nodes.Trees010.geometry}
        material={materials["New Tree"]}
        position={[-23.76, 12.88, -167.5]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees011"
        geometry={nodes.Trees011.geometry}
        material={materials["New Tree"]}
        position={[-26.73, 12.88, -161.28]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees012"
        geometry={nodes.Trees012.geometry}
        material={materials["New Tree"]}
        position={[-15.84, 12.88, -162.13]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees013"
        geometry={nodes.Trees013.geometry}
        material={materials["New Tree"]}
        position={[-14.65, 12.88, -154.49]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees014"
        geometry={nodes.Trees014.geometry}
        material={materials["New Tree"]}
        position={[-0.9, 12.88, -154.15]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees015"
        geometry={nodes.Trees015.geometry}
        material={materials["New Tree"]}
        position={[-7.69, 12.88, -150.41]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees016"
        geometry={nodes.Trees016.geometry}
        material={materials["New Tree"]}
        position={[1.31, 12.88, -144.98]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees017"
        geometry={nodes.Trees017.geometry}
        material={materials["New Tree"]}
        position={[12.55, 12.88, -144.74]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees018"
        geometry={nodes.Trees018.geometry}
        material={materials["New Tree"]}
        position={[18.66, 12.88, -136.43]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees019"
        geometry={nodes.Trees019.geometry}
        material={materials["New Tree"]}
        position={[25.5, 12.88, -133.49]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees020"
        geometry={nodes.Trees020.geometry}
        material={materials["New Tree"]}
        position={[33.08, 12.88, -127.14]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees021"
        geometry={nodes.Trees021.geometry}
        material={materials["New Tree"]}
        position={[37.97, 12.88, -127.63]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees022"
        geometry={nodes.Trees022.geometry}
        material={materials["New Tree"]}
        position={[47.99, 12.88, -119.67]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees023"
        geometry={nodes.Trees023.geometry}
        material={materials["New Tree"]}
        position={[59.31, 12.88, -114.44]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees024"
        geometry={nodes.Trees024.geometry}
        material={materials["New Tree"]}
        position={[70.34, 12.88, -107.08]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees025"
        geometry={nodes.Trees025.geometry}
        material={materials["New Tree"]}
        position={[85.33, 12.88, -94.92]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees026"
        geometry={nodes.Trees026.geometry}
        material={materials["New Tree"]}
        position={[98.63, 12.88, -87.85]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees027"
        geometry={nodes.Trees027.geometry}
        material={materials["New Tree"]}
        position={[110.09, 12.88, -78.09]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees028"
        geometry={nodes.Trees028.geometry}
        material={materials["New Tree"]}
        position={[129.84, 12.88, -58.53]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees029"
        geometry={nodes.Trees029.geometry}
        material={materials["New Tree"]}
        position={[124.96, 12.88, -68.1]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees030"
        geometry={nodes.Trees030.geometry}
        material={materials["New Tree"]}
        position={[143.29, 12.88, -48.55]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees031"
        geometry={nodes.Trees031.geometry}
        material={materials["New Tree"]}
        position={[131.68, 12.88, -49.16]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees032"
        geometry={nodes.Trees032.geometry}
        material={materials["New Tree"]}
        position={[137.38, 12.88, -55.48]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees033"
        geometry={nodes.Trees033.geometry}
        material={materials["New Tree"]}
        position={[140.44, 12.88, -38.16]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees034"
        geometry={nodes.Trees034.geometry}
        material={materials["New Tree"]}
        position={[149.19, 12.88, -24.31]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees035"
        geometry={nodes.Trees035.geometry}
        material={materials["New Tree"]}
        position={[136.16, 12.88, -26.96]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees036"
        geometry={nodes.Trees036.geometry}
        material={materials["New Tree"]}
        position={[146.14, 12.88, -32.66]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees037"
        geometry={nodes.Trees037.geometry}
        material={materials["New Tree"]}
        position={[160.19, 12.88, -38.16]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees038"
        geometry={nodes.Trees038.geometry}
        material={materials["New Tree"]}
        position={[151.64, 12.88, -47.53]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees039"
        geometry={nodes.Trees039.geometry}
        material={materials["New Tree"]}
        position={[161.01, 12.88, -27.57]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees040"
        geometry={nodes.Trees040.geometry}
        material={materials["New Tree"]}
        position={[131.88, 12.88, 14.39]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees041"
        geometry={nodes.Trees041.geometry}
        material={materials["New Tree"]}
        position={[140.68, 12.88, 23.78]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees042"
        geometry={nodes.Trees042.geometry}
        material={materials["New Tree"]}
        position={[132.17, 12.88, 26.71]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees043"
        geometry={nodes.Trees043.geometry}
        material={materials["New Tree"]}
        position={[132.17, 12.88, 37.27]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees044"
        geometry={nodes.Trees044.geometry}
        material={materials["New Tree"]}
        position={[128.1, 12.88, 50.17]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees045"
        geometry={nodes.Trees045.geometry}
        material={materials["New Tree"]}
        position={[122.19, 12.88, 62.8]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees046"
        geometry={nodes.Trees046.geometry}
        material={materials["New Tree"]}
        position={[111.81, 12.88, 79.91]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees047"
        geometry={nodes.Trees047.geometry}
        material={materials["New Tree"]}
        position={[105.08, 12.88, 90.7]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees048"
        geometry={nodes.Trees048.geometry}
        material={materials["New Tree"]}
        position={[95.51, 12.88, 108.83]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees049"
        geometry={nodes.Trees049.geometry}
        material={materials["New Tree"]}
        position={[84.71, 12.88, 126.96]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees050"
        geometry={nodes.Trees050.geometry}
        material={materials["New Tree"]}
        position={[75.96, 12.88, 142.03]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees051"
        geometry={nodes.Trees051.geometry}
        material={materials["New Tree"]}
        position={[68.01, 12.88, 156.49]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees052"
        geometry={nodes.Trees052.geometry}
        material={materials["New Tree"]}
        position={[59.46, 12.88, 171.77]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees053"
        geometry={nodes.Trees053.geometry}
        material={materials["New Tree"]}
        position={[48.87, 12.88, 190.51]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees054"
        geometry={nodes.Trees054.geometry}
        material={materials["New Tree"]}
        position={[36.85, 12.88, 212.51]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees055"
        geometry={nodes.Trees055.geometry}
        material={materials["New Tree"]}
        position={[26.46, 12.88, 231.04]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees056"
        geometry={nodes.Trees056.geometry}
        material={materials["New Tree"]}
        position={[17.9, 12.88, 243.87]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees057"
        geometry={nodes.Trees057.geometry}
        material={materials["New Tree"]}
        position={[10.16, 12.88, 260.58]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees058"
        geometry={nodes.Trees058.geometry}
        material={materials["New Tree"]}
        position={[0.39, 12.88, 274.43]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees059"
        geometry={nodes.Trees059.geometry}
        material={materials["New Tree"]}
        position={[-6.33, 12.88, 286.04]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees060"
        geometry={nodes.Trees060.geometry}
        material={materials["New Tree"]}
        position={[-9.8, 12.88, 294.19]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees061"
        geometry={nodes.Trees061.geometry}
        material={materials["New Tree"]}
        position={[-16.31, 12.88, 305.39]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees062"
        geometry={nodes.Trees062.geometry}
        material={materials["New Tree"]}
        position={[-21.2, 12.88, 315.98]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees063"
        geometry={nodes.Trees063.geometry}
        material={materials["New Tree"]}
        position={[-27.72, 12.88, 326.57]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees064"
        geometry={nodes.Trees064.geometry}
        material={materials["New Tree"]}
        position={[-39.74, 12.88, 342.05]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees065"
        geometry={nodes.Trees065.geometry}
        material={materials["New Tree"]}
        position={[-120.2, 12.88, 345.11]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees066"
        geometry={nodes.Trees066.geometry}
        material={materials["New Tree"]}
        position={[-97.38, 12.88, 355.09]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees067"
        geometry={nodes.Trees067.geometry}
        material={materials["New Tree"]}
        position={[-110.21, 12.88, 358.76]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees068"
        geometry={nodes.Trees068.geometry}
        material={materials["New Tree"]}
        position={[-106.34, 12.88, 351.63]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees069"
        geometry={nodes.Trees069.geometry}
        material={materials["New Tree"]}
        position={[-121.62, 12.88, 356.51]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees070"
        geometry={nodes.Trees070.geometry}
        material={materials["New Tree"]}
        position={[-75.59, 12.88, 357.53]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees071"
        geometry={nodes.Trees071.geometry}
        material={materials["New Tree"]}
        position={[-94.12, 12.88, 344.09]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees072"
        geometry={nodes.Trees072.geometry}
        material={materials["New Tree"]}
        position={[-84.35, 12.88, 374.24]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees073"
        geometry={nodes.Trees073.geometry}
        material={materials["New Tree"]}
        position={[-110.62, 12.88, 374.03]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees074"
        geometry={nodes.Trees074.geometry}
        material={materials["New Tree"]}
        position={[-90.05, 12.88, 361.2]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees075"
        geometry={nodes.Trees075.geometry}
        material={materials["New Tree"]}
        position={[-122.44, 12.88, 367.72]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees076"
        geometry={nodes.Trees076.geometry}
        material={materials["New Tree"]}
        position={[-105.73, 12.88, 392.77]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees077"
        geometry={nodes.Trees077.geometry}
        material={materials["New Tree"]}
        position={[-68.05, 12.88, 377.09]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees078"
        geometry={nodes.Trees078.geometry}
        material={materials["New Tree"]}
        position={[-56.64, 12.88, 353.26]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees079"
        geometry={nodes.Trees079.geometry}
        material={materials["New Tree"]}
        position={[-78.44, 12.88, 392.77]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees080"
        geometry={nodes.Trees080.geometry}
        material={materials["New Tree"]}
        position={[-125.49, 12.88, 397.25]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees081"
        geometry={nodes.Trees081.geometry}
        material={materials["New Tree"]}
        position={[-120.4, 12.88, 418.44]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees082"
        geometry={nodes.Trees082.geometry}
        material={materials["New Tree"]}
        position={[-97.59, 12.88, 417.42]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees083"
        geometry={nodes.Trees083.geometry}
        material={materials["New Tree"]}
        position={[-138.93, 12.88, 435.95]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees084"
        geometry={nodes.Trees084.geometry}
        material={materials["New Tree"]}
        position={[-162.56, 12.88, 415.18]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees085"
        geometry={nodes.Trees085.geometry}
        material={materials["New Tree"]}
        position={[-111.03, 12.88, 434.32]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees086"
        geometry={nodes.Trees086.geometry}
        material={materials["New Tree"]}
        position={[-142.81, 12.88, 454.08]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees087"
        geometry={nodes.Trees087.geometry}
        material={materials["New Tree"]}
        position={[-142.81, 12.88, 422.1]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees088"
        geometry={nodes.Trees088.geometry}
        material={materials["New Tree"]}
        position={[-106.34, 12.88, 461.62]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees089"
        geometry={nodes.Trees089.geometry}
        material={materials["New Tree"]}
        position={[-161.54, 12.88, 438.6]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees090"
        geometry={nodes.Trees090.geometry}
        material={materials["New Tree"]}
        position={[-133.23, 12.88, 466.51]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees091"
        geometry={nodes.Trees091.geometry}
        material={materials["New Tree"]}
        position={[-127.53, 12.88, 445.32]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees092"
        geometry={nodes.Trees092.geometry}
        material={materials["New Tree"]}
        position={[-161.34, 12.88, 459.78]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees093"
        geometry={nodes.Trees093.geometry}
        material={materials["New Tree"]}
        position={[-137.71, 12.88, 484.84]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees094"
        geometry={nodes.Trees094.geometry}
        material={materials["New Tree"]}
        position={[-96.36, 12.88, 442.27]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees095"
        geometry={nodes.Trees095.geometry}
        material={materials["New Tree"]}
        position={[-178.04, 12.88, 425.56]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees096"
        geometry={nodes.Trees096.geometry}
        material={materials["New Tree"]}
        position={[-191.69, 12.88, 415.38]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees097"
        geometry={nodes.Trees097.geometry}
        material={materials["New Tree"]}
        position={[-244.85, 12.88, 343.27]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees098"
        geometry={nodes.Trees098.geometry}
        material={materials["New Tree"]}
        position={[-232.84, 12.88, 342.46]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees099"
        geometry={nodes.Trees099.geometry}
        material={materials["New Tree"]}
        position={[-219.6, 12.88, 342.46]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees100"
        geometry={nodes.Trees100.geometry}
        material={materials["New Tree"]}
        position={[-205.54, 12.88, 343.68]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees101"
        geometry={nodes.Trees101.geometry}
        material={materials["New Tree"]}
        position={[-174.38, 12.88, 343.89]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees102"
        geometry={nodes.Trees102.geometry}
        material={materials["New Tree"]}
        position={[-159.1, 12.88, 344.09]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees103"
        geometry={nodes.Trees103.geometry}
        material={materials["New Tree"]}
        position={[-211.24, 12.88, 290.72]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees104"
        geometry={nodes.Trees104.geometry}
        material={materials["New Tree"]}
        position={[-199.43, 12.88, 288.89]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees105"
        geometry={nodes.Trees105.geometry}
        material={materials["New Tree"]}
        position={[-215.93, 12.88, 305.59]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees106"
        geometry={nodes.Trees106.geometry}
        material={materials["New Tree"]}
        position={[-196.37, 12.88, 300.5]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees107"
        geometry={nodes.Trees107.geometry}
        material={materials["New Tree"]}
        position={[-204.93, 12.88, 300.09]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees108"
        geometry={nodes.Trees108.geometry}
        material={materials["New Tree"]}
        position={[-201.67, 12.88, 314.96]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees109"
        geometry={nodes.Trees109.geometry}
        material={materials["New Tree"]}
        position={[-221.02, 12.88, 317.2]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees110"
        geometry={nodes.Trees110.geometry}
        material={materials["New Tree"]}
        position={[-189.65, 12.88, 307.83]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees111"
        geometry={nodes.Trees111.geometry}
        material={materials["New Tree"]}
        position={[-218.37, 12.88, 282.98]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees112"
        geometry={nodes.Trees112.geometry}
        material={materials["New Tree"]}
        position={[-207.78, 12.88, 320.26]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees113"
        geometry={nodes.Trees113.geometry}
        material={materials["New Tree"]}
        position={[-100.34, 12.88, 309.73]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees114"
        geometry={nodes.Trees114.geometry}
        material={materials["New Tree"]}
        position={[-75.38, 12.88, 309.22]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees115"
        geometry={nodes.Trees115.geometry}
        material={materials["New Tree"]}
        position={[-74.9, 12.88, 301.65]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees116"
        geometry={nodes.Trees116.geometry}
        material={materials["New Tree"]}
        position={[-89.07, 12.88, 307.51]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees117"
        geometry={nodes.Trees117.geometry}
        material={materials["New Tree"]}
        position={[-73.67, 12.88, 323.16]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees118"
        geometry={nodes.Trees118.geometry}
        material={materials["New Tree"]}
        position={[-56.07, 12.88, 313.14]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees119"
        geometry={nodes.Trees119.geometry}
        material={materials["New Tree"]}
        position={[-62.92, 12.88, 304.34]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees120"
        geometry={nodes.Trees120.geometry}
        material={materials["New Tree"]}
        position={[-87.36, 12.88, 319.74]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees121"
        geometry={nodes.Trees121.geometry}
        material={materials["New Tree"]}
        position={[-87.61, 12.88, 319.74]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees122"
        geometry={nodes.Trees122.geometry}
        material={materials["New Tree"]}
        position={[-59.74, 12.88, 320.96]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees123"
        geometry={nodes.Trees123.geometry}
        material={materials["New Tree"]}
        position={[-41.41, 12.88, 304.58]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees124"
        geometry={nodes.Trees124.geometry}
        material={materials["New Tree"]}
        position={[-56.07, 12.88, 295.29]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees125"
        geometry={nodes.Trees125.geometry}
        material={materials["New Tree"]}
        position={[-33.27, 12.88, 294.28]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees126"
        geometry={nodes.Trees126.geometry}
        material={materials["New Tree"]}
        position={[-236, 12.88, 209.64]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees127"
        geometry={nodes.Trees127.geometry}
        material={materials["New Tree"]}
        position={[-217.33, 12.88, 205.39]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees128"
        geometry={nodes.Trees128.geometry}
        material={materials["New Tree"]}
        position={[-230.91, 12.88, 198.94]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees129"
        geometry={nodes.Trees129.geometry}
        material={materials["New Tree"]}
        position={[-215.97, 12.88, 221.18]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees130"
        geometry={nodes.Trees130.geometry}
        material={materials["New Tree"]}
        position={[-198.49, 12.88, 207.94]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees131"
        geometry={nodes.Trees131.geometry}
        material={materials["New Tree"]}
        position={[-221.91, 12.88, 222.54]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees132"
        geometry={nodes.Trees132.geometry}
        material={materials["New Tree"]}
        position={[-240.25, 12.88, 223.56]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees133"
        geometry={nodes.Trees133.geometry}
        material={materials["New Tree"]}
        position={[-269.27, 12.88, 200.98]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees134"
        geometry={nodes.Trees134.geometry}
        material={materials["New Tree"]}
        position={[-274.02, 12.88, 214.73]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees135"
        geometry={nodes.Trees135.geometry}
        material={materials["New Tree"]}
        position={[-280.31, 12.88, 231.36]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees136"
        geometry={nodes.Trees136.geometry}
        material={materials["New Tree"]}
        position={[-266.56, 12.88, 234.59]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees137"
        geometry={nodes.Trees137.geometry}
        material={materials["New Tree"]}
        position={[-267.74, 12.88, 224.23]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees138"
        geometry={nodes.Trees138.geometry}
        material={materials["New Tree"]}
        position={[-274.87, 12.88, 224.4]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees139"
        geometry={nodes.Trees139.geometry}
        material={materials["New Tree"]}
        position={[-267.07, 12.88, 210.49]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees140"
        geometry={nodes.Trees140.geometry}
        material={materials["New Tree"]}
        position={[-185.93, 12.88, 201.15]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees141"
        geometry={nodes.Trees141.geometry}
        material={materials["New Tree"]}
        position={[-213.77, 12.88, 148.02]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees142"
        geometry={nodes.Trees142.geometry}
        material={materials["New Tree"]}
        position={[-230.74, 12.88, 152.09]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees143"
        geometry={nodes.Trees143.geometry}
        material={materials["New Tree"]}
        position={[-223.1, 12.88, 143.27]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees144"
        geometry={nodes.Trees144.geometry}
        material={materials["New Tree"]}
        position={[-246.87, 12.88, 152.6]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees145"
        geometry={nodes.Trees145.geometry}
        material={materials["New Tree"]}
        position={[-217.5, 12.88, 113.39]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees146"
        geometry={nodes.Trees146.geometry}
        material={materials["New Tree"]}
        position={[-226.33, 12.88, 111.87]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees147"
        geometry={nodes.Trees147.geometry}
        material={materials["New Tree"]}
        position={[-216.31, 12.88, 95.91]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees148"
        geometry={nodes.Trees148.geometry}
        material={materials["New Tree"]}
        position={[-213.77, 12.88, 82.67]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees149"
        geometry={nodes.Trees149.geometry}
        material={materials["New Tree"]}
        position={[-196.79, 12.88, 111.19]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees150"
        geometry={nodes.Trees150.geometry}
        material={materials["New Tree"]}
        position={[-180.67, 12.88, 107.28]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees151"
        geometry={nodes.Trees151.geometry}
        material={materials["New Tree"]}
        position={[-190.34, 12.88, 91.33]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees152"
        geometry={nodes.Trees152.geometry}
        material={materials["New Tree"]}
        position={[-198.15, 12.88, 91.67]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees153"
        geometry={nodes.Trees153.geometry}
        material={materials["New Tree"]}
        position={[-182.7, 12.88, 76.05]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees154"
        geometry={nodes.Trees154.geometry}
        material={materials["New Tree"]}
        position={[-196.45, 12.88, 64.85]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees155"
        geometry={nodes.Trees155.geometry}
        material={materials["New Tree"]}
        position={[-185.59, 12.88, 44.65]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees156"
        geometry={nodes.Trees156.geometry}
        material={materials["New Tree"]}
        position={[-194.08, 12.88, 38.54]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees157"
        geometry={nodes.Trees157.geometry}
        material={materials["New Tree"]}
        position={[-193.23, 12.88, 57.72]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees158"
        geometry={nodes.Trees158.geometry}
        material={materials["New Tree"]}
        position={[-176.22, 12.88, 10.79]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees159"
        geometry={nodes.Trees159.geometry}
        material={materials["New Tree"]}
        position={[-172.54, 12.88, -1.94]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees160"
        geometry={nodes.Trees160.geometry}
        material={materials["New Tree"]}
        position={[-166.6, 12.88, -14.81]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees161"
        geometry={nodes.Trees161.geometry}
        material={materials["New Tree"]}
        position={[-162.35, 12.88, -25.42]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees162"
        geometry={nodes.Trees162.geometry}
        material={materials["New Tree"]}
        position={[-167.16, 12.88, 11.64]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees163"
        geometry={nodes.Trees163.geometry}
        material={materials["New Tree"]}
        position={[-153.58, 12.88, 11.36]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees164"
        geometry={nodes.Trees164.geometry}
        material={materials["New Tree"]}
        position={[-140.29, 12.88, 11.5]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees165"
        geometry={nodes.Trees165.geometry}
        material={materials["New Tree"]}
        position={[-131.94, 12.88, 11.36]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees166"
        geometry={nodes.Trees166.geometry}
        material={materials["New Tree"]}
        position={[-132.23, 12.88, 3.72]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees167"
        geometry={nodes.Trees167.geometry}
        material={materials["New Tree"]}
        position={[-132.65, 12.88, -10.29]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees168"
        geometry={nodes.Trees168.geometry}
        material={materials["New Tree"]}
        position={[-132.93, 12.88, -24.86]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees169"
        geometry={nodes.Trees169.geometry}
        material={materials["New Tree"]}
        position={[-149.07, 12.88, -50.77]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees170"
        geometry={nodes.Trees170.geometry}
        material={materials["New Tree"]}
        position={[-140.51, 12.88, -67.14]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees171"
        geometry={nodes.Trees171.geometry}
        material={materials["New Tree"]}
        position={[-132.44, 12.88, -80.34]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees172"
        geometry={nodes.Trees172.geometry}
        material={materials["New Tree"]}
        position={[-127.07, 12.88, -92.32]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees173"
        geometry={nodes.Trees173.geometry}
        material={materials["New Tree"]}
        position={[-113.38, 12.88, -93.3]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees174"
        geometry={nodes.Trees174.geometry}
        material={materials["New Tree"]}
        position={[-96.02, 12.88, -93.3]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees175"
        geometry={nodes.Trees175.geometry}
        material={materials["New Tree"]}
        position={[-135.87, 12.88, -47.59]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees176"
        geometry={nodes.Trees176.geometry}
        material={materials["New Tree"]}
        position={[-119, 12.88, -46.85]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees177"
        geometry={nodes.Trees177.geometry}
        material={materials["New Tree"]}
        position={[-105.31, 12.88, -46.61]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees178"
        geometry={nodes.Trees178.geometry}
        material={materials["New Tree"]}
        position={[-88.69, 12.88, -46.85]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees179"
        geometry={nodes.Trees179.geometry}
        material={materials["New Tree"]}
        position={[-68.89, 12.88, -47.1]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees180"
        geometry={nodes.Trees180.geometry}
        material={materials["New Tree"]}
        position={[-53.74, 12.88, -47.1]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees181"
        geometry={nodes.Trees181.geometry}
        material={materials["New Tree"]}
        position={[-51.78, 12.88, -56.39]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees182"
        geometry={nodes.Trees182.geometry}
        material={materials["New Tree"]}
        position={[-51.29, 12.88, -66.65]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees183"
        geometry={nodes.Trees183.geometry}
        material={materials["New Tree"]}
        position={[-96.95, 12.88, -115.71]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees184"
        geometry={nodes.Trees184.geometry}
        material={materials["New Tree"]}
        position={[-97.46, 12.88, -128.78]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees185"
        geometry={nodes.Trees185.geometry}
        material={materials["New Tree"]}
        position={[-110.7, 12.88, -129.63]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees186"
        geometry={nodes.Trees186.geometry}
        material={materials["New Tree"]}
        position={[-116.64, 12.88, -122.67]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees187"
        geometry={nodes.Trees187.geometry}
        material={materials["New Tree"]}
        position={[-109.86, 12.88, -116.39]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees188"
        geometry={nodes.Trees188.geometry}
        material={materials["New Tree"]}
        position={[-118.51, 12.88, -114.69]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees189"
        geometry={nodes.Trees189.geometry}
        material={materials["New Tree"]}
        position={[-32.47, 12.88, -136.2]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees190"
        geometry={nodes.Trees190.geometry}
        material={materials["New Tree"]}
        position={[-21.23, 12.88, -131.55]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees191"
        geometry={nodes.Trees191.geometry}
        material={materials["New Tree"]}
        position={[15.43, 12.88, -97.58]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees192"
        geometry={nodes.Trees192.geometry}
        material={materials["New Tree"]}
        position={[27.65, 12.88, -97.58]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees193"
        geometry={nodes.Trees193.geometry}
        material={materials["New Tree"]}
        position={[43.3, 12.88, -97.82]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees194"
        geometry={nodes.Trees194.geometry}
        material={materials["New Tree"]}
        position={[79.76, 12.88, -71.96]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees195"
        geometry={nodes.Trees195.geometry}
        material={materials["New Tree"]}
        position={[80.98, 12.88, -48.74]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees196"
        geometry={nodes.Trees196.geometry}
        material={materials["New Tree"]}
        position={[80.17, 12.88, -34.07]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees197"
        geometry={nodes.Trees197.geometry}
        material={materials["New Tree"]}
        position={[79.35, 12.88, -16.35]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees198"
        geometry={nodes.Trees198.geometry}
        material={materials["New Tree"]}
        position={[72.02, 12.88, 3]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees199"
        geometry={nodes.Trees199.geometry}
        material={materials["New Tree"]}
        position={[79.35, 12.88, 10.54]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees200"
        geometry={nodes.Trees200.geometry}
        material={materials["New Tree"]}
        position={[93.61, 12.88, 11.35]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees201"
        geometry={nodes.Trees201.geometry}
        material={materials["New Tree"]}
        position={[106.85, 12.88, 13.19]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees202"
        geometry={nodes.Trees202.geometry}
        material={materials["New Tree"]}
        position={[112.76, 12.88, 3.82]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees203"
        geometry={nodes.Trees203.geometry}
        material={materials["New Tree"]}
        position={[112.76, 12.88, -14.52]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees204"
        geometry={nodes.Trees204.geometry}
        material={materials["New Tree"]}
        position={[108.68, 12.88, -28.16]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees205"
        geometry={nodes.Trees205.geometry}
        material={materials["New Tree"]}
        position={[107.66, 12.88, -35.29]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees206"
        geometry={nodes.Trees206.geometry}
        material={materials["New Tree"]}
        position={[102.16, 12.88, -49.14]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees207"
        geometry={nodes.Trees207.geometry}
        material={materials["New Tree"]}
        position={[93.41, 12.88, -68.7]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees208"
        geometry={nodes.Trees208.geometry}
        material={materials["New Tree"]}
        position={[83.14, 12.88, -78.96]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees209"
        geometry={nodes.Trees209.geometry}
        material={materials["New Tree"]}
        position={[111.98, 12.88, 30.05]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees210"
        geometry={nodes.Trees210.geometry}
        material={materials["New Tree"]}
        position={[102.94, 12.88, 29.32]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees211"
        geometry={nodes.Trees211.geometry}
        material={materials["New Tree"]}
        position={[110.03, 12.88, 41.05]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees212"
        geometry={nodes.Trees212.geometry}
        material={materials["New Tree"]}
        position={[103.18, 12.88, 35.67]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees213"
        geometry={nodes.Trees213.geometry}
        material={materials["New Tree"]}
        position={[103.67, 12.88, 48.87]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees214"
        geometry={nodes.Trees214.geometry}
        material={materials["New Tree"]}
        position={[96.83, 12.88, 33.23]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees215"
        geometry={nodes.Trees215.geometry}
        material={materials["New Tree"]}
        position={[95.36, 12.88, 42.52]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees216"
        geometry={nodes.Trees216.geometry}
        material={materials["New Tree"]}
        position={[104.16, 12.88, 57.92]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
      <mesh
        name="Trees217"
        geometry={nodes.Trees217.geometry}
        material={materials["New Tree"]}
        position={[88.52, 12.88, 31.27]}
        rotation={[-0.04, 1.16, 0.02]}
        scale={[1.27, 1.15, 1.39]}
      />
    </group>
  );
}
