/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Part6(props) {
  const { nodes, materials } = useGLTF("/assets/part6.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Hall_003010"
        geometry={nodes.Hall_003010.geometry}
        material={materials.adminbake}
        position={[-42.03, 14.04, -95.43]}
        scale={15.09}
      />
      <mesh
        name="Hall_004"
        geometry={nodes.Hall_004.geometry}
        material={materials.sb}
        position={[-93.64, 11.33, 55.58]}
        scale={[-0.13, -1.47, -0.13]}
      />
    </group>
  );
}

