/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Part3(props) {
  const { nodes, materials } = useGLTF("/assets/part3.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        name="light"
        geometry={nodes.light.geometry}
        material={materials["LampPost.001"]}
        position={[-106.4, 14.28, 73.87]}
        scale={15.09}
      />
    </group>
  );
}

