/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Part4(props) {
  const { nodes, materials } = useGLTF("/assets/part4.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        name="hall001"
        geometry={nodes.hall001.geometry}
        material={materials.NEWLAB}
        position={[5.52, 24.22, -12.37]}
        scale={15.09}
      />
    </group>
  );
}
