/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Part9(props) {
  const { nodes, materials } = useGLTF("/assets/part9.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Cube035"
        geometry={nodes.Cube035.geometry}
        material={materials.Text}
        position={[-12.82, 11.66, 0.19]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="text005"
        geometry={nodes.text005.geometry}
        material={materials.Text}
        position={[-12.73, 11.66, -1.67]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="Cube037"
        geometry={nodes.Cube037.geometry}
        material={materials.Text}
        position={[-7.66, 11.66, 3.8]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="Cube045"
        geometry={nodes.Cube045.geometry}
        material={materials.Text}
        position={[-10.33, 11.66, 3.88]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="Cube055"
        geometry={nodes.Cube055.geometry}
        material={materials.Text}
        position={[-12.81, 11.66, 3.9]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="stall004"
        geometry={nodes.stall004.geometry}
        material={materials["Benches.002"]}
        position={[-12.85, 11.43, 1.92]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.68, 0.84, 1.57]}
      />
      <mesh
        name="Cube030"
        geometry={nodes.Cube030.geometry}
        material={materials.Text}
        position={[-12.22, 11.66, -4.09]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="Cube040"
        geometry={nodes.Cube040.geometry}
        material={materials.Text}
        position={[-9.54, 11.66, -4.05]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="Cube043"
        geometry={nodes.Cube043.geometry}
        material={materials.Text}
        position={[-6.74, 11.66, -4.08]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="Cube046"
        geometry={nodes.Cube046.geometry}
        material={materials.Text}
        position={[-4.04, 11.66, -4.12]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="Cube064"
        geometry={nodes.Cube064.geometry}
        material={materials.Text}
        position={[-1.57, 11.66, -4.09]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="Cube065"
        geometry={nodes.Cube065.geometry}
        material={materials.Text}
        position={[1.2, 11.66, -4.1]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="Cube066"
        geometry={nodes.Cube066.geometry}
        material={materials.Text}
        position={[3.95, 11.66, -4.08]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="Cube067"
        geometry={nodes.Cube067.geometry}
        material={materials.Text}
        position={[6.61, 11.66, -4.08]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="Cube068"
        geometry={nodes.Cube068.geometry}
        material={materials.Text}
        position={[9.26, 11.66, -4.05]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="Cube069"
        geometry={nodes.Cube069.geometry}
        material={materials.Text}
        position={[12.05, 11.66, -4.12]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="Cube070"
        geometry={nodes.Cube070.geometry}
        material={materials.Text}
        position={[14.72, 11.66, -4.01]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="Cube071"
        geometry={nodes.Cube071.geometry}
        material={materials.Text}
        position={[17.41, 11.66, -4.02]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="Cube072"
        geometry={nodes.Cube072.geometry}
        material={materials.Text}
        position={[-3.76, 11.66, -0.16]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="Cube073"
        geometry={nodes.Cube073.geometry}
        material={materials.Text}
        position={[20.02, 11.66, -4.05]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="Cube074"
        geometry={nodes.Cube074.geometry}
        material={materials.Text}
        position={[-5.35, 11.66, 3.71]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="Cube075"
        geometry={nodes.Cube075.geometry}
        material={materials.Text}
        position={[-2.75, 11.66, 3.7]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="Cube076"
        geometry={nodes.Cube076.geometry}
        material={materials.Text}
        position={[0.11, 11.66, 3.82]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="Cube077"
        geometry={nodes.Cube077.geometry}
        material={materials.Text}
        position={[2.85, 11.66, 3.8]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="Cube078"
        geometry={nodes.Cube078.geometry}
        material={materials.Text}
        position={[5.59, 11.66, 3.75]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="Cube079"
        geometry={nodes.Cube079.geometry}
        material={materials.Text}
        position={[7.99, 11.66, 3.8]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="Cube080"
        geometry={nodes.Cube080.geometry}
        material={materials.Text}
        position={[10.91, 11.66, 3.77]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="Cube081"
        geometry={nodes.Cube081.geometry}
        material={materials.Text}
        position={[13.62, 11.66, 3.83]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="Cube082"
        geometry={nodes.Cube082.geometry}
        material={materials.Text}
        position={[16.39, 11.66, 3.79]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="Cube083"
        geometry={nodes.Cube083.geometry}
        material={materials.Text}
        position={[19.03, 11.66, 3.82]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="Cube084"
        geometry={nodes.Cube084.geometry}
        material={materials.Text}
        position={[12.06, 11.66, -0.14]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="Cube085"
        geometry={nodes.Cube085.geometry}
        material={materials.Text}
        position={[21.65, 11.66, 3.75]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="Cube086"
        geometry={nodes.Cube086.geometry}
        material={materials.Text}
        position={[21.69, 11.66, 0.97]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="Cube087"
        geometry={nodes.Cube087.geometry}
        material={materials.Text}
        position={[21.63, 11.66, -0.99]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="stall005"
        geometry={nodes.stall005.geometry}
        material={materials["Benches.004"]}
        position={[-12.27, 11.43, -4.06]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="stall002"
        geometry={nodes.stall002.geometry}
        material={materials["Benches.004"]}
        position={[-12.85, 11.43, 0.09]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="stall001"
        geometry={nodes.stall001.geometry}
        material={materials["Benches.004"]}
        position={[-12.86, 11.43, -1.74]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="stall006"
        geometry={nodes.stall006.geometry}
        material={materials["Benches.004"]}
        position={[-7.79, 11.43, 3.77]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="stall007"
        geometry={nodes.stall007.geometry}
        material={materials["Benches.003"]}
        position={[-10.33, 11.43, 3.76]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="stall003"
        geometry={nodes.stall003.geometry}
        material={materials["Benches.004"]}
        position={[-12.87, 11.43, 3.76]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="Text017"
        geometry={nodes.Text017.geometry}
        material={materials.Text}
        position={[-12.85, 11.66, 1.9]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.68, 0.84, 1.57]}
      />
      <mesh
        name="stall008"
        geometry={nodes.stall008.geometry}
        material={materials["Benches.004"]}
        position={[-9.58, 11.43, -4.06]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="stall009"
        geometry={nodes.stall009.geometry}
        material={materials["Benches.004"]}
        position={[-6.88, 11.43, -4.06]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="stall010"
        geometry={nodes.stall010.geometry}
        material={materials["Benches.004"]}
        position={[-4.18, 11.43, -4.06]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="stall011"
        geometry={nodes.stall011.geometry}
        material={materials.Benches}
        position={[-1.49, 11.43, -4.06]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="stall012"
        geometry={nodes.stall012.geometry}
        material={materials.Benches}
        position={[1.21, 11.43, -4.06]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="stall013"
        geometry={nodes.stall013.geometry}
        material={materials["Benches.003"]}
        position={[3.91, 11.43, -4.06]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="stall014"
        geometry={nodes.stall014.geometry}
        material={materials["Benches.003"]}
        position={[6.61, 11.43, -4.06]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="stall015"
        geometry={nodes.stall015.geometry}
        material={materials["Benches.003"]}
        position={[9.31, 11.43, -4.06]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="stall016"
        geometry={nodes.stall016.geometry}
        material={materials["Benches.003"]}
        position={[12.01, 11.43, -4.06]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="stall017"
        geometry={nodes.stall017.geometry}
        material={materials["Benches.003"]}
        position={[14.71, 11.43, -4.06]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="stall018"
        geometry={nodes.stall018.geometry}
        material={materials["Benches.003"]}
        position={[17.41, 11.43, -4.06]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="stall019"
        geometry={nodes.stall019.geometry}
        material={materials["Benches.001"]}
        position={[-3.84, 11.43, -0.09]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="stall020"
        geometry={nodes.stall020.geometry}
        material={materials["Benches.001"]}
        position={[19.98, 11.43, -4.04]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="stall021"
        geometry={nodes.stall021.geometry}
        material={materials["Benches.004"]}
        position={[-5.32, 11.43, 3.76]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="stall022"
        geometry={nodes.stall022.geometry}
        material={materials["Benches.004"]}
        position={[-2.62, 11.43, 3.75]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="stall023"
        geometry={nodes.stall023.geometry}
        material={materials["Benches.005"]}
        position={[0.06, 11.43, 3.76]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="stall024"
        geometry={nodes.stall024.geometry}
        material={materials["Benches.001"]}
        position={[2.76, 11.43, 3.76]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="stall025"
        geometry={nodes.stall025.geometry}
        material={materials["Benches.001"]}
        position={[5.46, 11.43, 3.76]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="stall026"
        geometry={nodes.stall026.geometry}
        material={materials["Benches.001"]}
        position={[8.15, 11.43, 3.76]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="stall027"
        geometry={nodes.stall027.geometry}
        material={materials["Benches.001"]}
        position={[10.85, 11.43, 3.76]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="stall028"
        geometry={nodes.stall028.geometry}
        material={materials["Benches.004"]}
        position={[13.55, 11.43, 3.76]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="stall029"
        geometry={nodes.stall029.geometry}
        material={materials["Benches.004"]}
        position={[16.25, 11.43, 3.76]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="stall030"
        geometry={nodes.stall030.geometry}
        material={materials["Benches.004"]}
        position={[18.95, 11.43, 3.76]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="stall031"
        geometry={nodes.stall031.geometry}
        material={materials["Benches.004"]}
        position={[12.02, 11.43, -0.06]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="stall032"
        geometry={nodes.stall032.geometry}
        material={materials["Benches.002"]}
        position={[21.68, 11.43, 3.76]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="stall033"
        geometry={nodes.stall033.geometry}
        material={materials["Benches.002"]}
        position={[21.63, 11.43, 0.99]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="stall034"
        geometry={nodes.stall034.geometry}
        material={materials["Benches.002"]}
        position={[21.56, 11.43, -0.98]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.84, 0.18, 1.04]}
      />
      <mesh
        name="stall035"
        geometry={nodes.stall035.geometry}
        material={materials["Benches.002"]}
        position={[0.25, 11.43, -0.09]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.68, 0.84, 1.57]}
      />
      <mesh
        name="Text046"
        geometry={nodes.Text046.geometry}
        material={materials.Text}
        position={[0.24, 11.66, -0.07]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.68, 0.84, 1.57]}
      />
      <mesh
        name="stall036"
        geometry={nodes.stall036.geometry}
        material={materials["Benches.002"]}
        position={[8.46, 11.43, -0.07]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.68, 0.84, 1.57]}
      />
      <mesh
        name="Text048"
        geometry={nodes.Text048.geometry}
        material={materials.Text}
        position={[8.45, 11.66, -0.06]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.68, 0.84, 1.57]}
      />
    </group>
  );
}
