/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, Text } from "@react-three/drei";

export function Board(props) {
  const { nodes, materials } = useGLTF("/assets/model/Wooden_Sign_BLEND.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sign_Base.geometry}
        material={materials.Chocofur_free_01_wood}
        position={[-0.01, 0.91, 0]}
        scale={0.37}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sign_Arrow.geometry}
        material={materials.Chocofur_free_01_wood}
        position={[0.03, 1.63, -0.01]}
        scale={1.61}
      >
        <Text anchorX="center" anchorY="middle">
          Game Zone
        </Text>
      </mesh>
    </group>
  );
}
