/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Car(props) {
  const { nodes, materials } = useGLTF("/assets/model/car.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_5.geometry}
        material={materials["Material.007"]}
        position={[-5.12, 3.66, -2.98]}
        rotation={[-1.57, 0, -Math.PI]}
        scale={3.17}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials["Material.004"]}
        position={[-5.12, 3.66, -2.98]}
        rotation={[-1.57, 0, -Math.PI]}
        scale={3.17}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials["Material.009"]}
        position={[0, -0.13, 0]}
        scale={[6.23, 7.94, 8.68]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_7.geometry}
        material={materials["Material.006"]}
        position={[-5.12, 3.66, -2.98]}
        rotation={[-1.57, 0, -Math.PI]}
        scale={3.17}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials["Material.005"]}
        position={[-5.12, 3.66, -2.98]}
        rotation={[-1.57, 0, -Math.PI]}
        scale={3.17}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials["Material.008"]}
        position={[-5.12, 3.66, -2.98]}
        rotation={[-1.57, 0, -Math.PI]}
        scale={3.17}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials["Material.001"]}
        position={[-5.12, 3.66, -2.98]}
        rotation={[-1.57, 0, -Math.PI]}
        scale={3.17}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_3.geometry}
        material={materials["Material.002"]}
        position={[-5.12, 3.66, -2.98]}
        rotation={[-1.57, 0, -Math.PI]}
        scale={3.17}
      />
    </group>
  );
}

// useGLTF.preload("/car.glb");
