/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo, useContext, createContext } from "react";
import { useGLTF, Merged } from "@react-three/drei";

const context = createContext();
export function InstancesDance({ children, ...props }) {
  const { nodes } = useGLTF("/assets/model/dance.glb");
  const instances = useMemo(
    () => ({
      Object: nodes.Object_4,
      Object1: nodes.Object_5,
      Object2: nodes.Object_7,
      Object3: nodes.Object_9,
      Object4: nodes.Object_10,
      Object5: nodes.Object_12,
      Object6: nodes.Object_13,
      Object7: nodes.Object_15,
      Object8: nodes.Object_16,
      Object9: nodes.Object_18,
      Object10: nodes.Object_19,
      Object11: nodes.Object_21,
      Object12: nodes.Object_22,
      Object13: nodes.Object_24,
      Object14: nodes.Object_25,
      Object15: nodes.Object_27,
      Object16: nodes.Object_29,
      Object17: nodes.Object_31,
      Object18: nodes.Object_33,
      Object19: nodes.Object_35,
      Object20: nodes.Object_37,
      Object21: nodes.Object_39,
      Object22: nodes.Object_41,
      Object23: nodes.Object_43,
      Object24: nodes.Object_45,
      Object25: nodes.Object_47,
      Object26: nodes.Object_49,
      Object27: nodes.Object_51,
      Object28: nodes.Object_53,
      Object29: nodes.Object_55,
      Object30: nodes.Object_57,
      Object31: nodes.Object_59,
      Object32: nodes.Object_61,
      Object33: nodes.Object_63,
      Object34: nodes.Object_65,
      Object35: nodes.Object_67,
      Object36: nodes.Object_69,
      Object37: nodes.Object_71,
      Object38: nodes.Object_73,
      Object39: nodes.Object_75,
      Object40: nodes.Object_76,
      Object41: nodes.Object_78,
      Object42: nodes.Object_79,
      Object43: nodes.Object_81,
      Object44: nodes.Object_83,
      Object45: nodes.Object_85,
      Object46: nodes.Object_87,
      Object47: nodes.Object_89,
      Object48: nodes.Object_91,
      Object49: nodes.Object_93,
      Object50: nodes.Object_95,
      Object51: nodes.Object_97,
      Object52: nodes.Object_99,
      Object53: nodes.Object_101,
      Object54: nodes.Object_103,
      Object55: nodes.Object_105,
      Object56: nodes.Object_107,
      Object57: nodes.Object_109,
      Object58: nodes.Object_111,
      Object59: nodes.Object_113,
      Object60: nodes.Object_114,
      Object61: nodes.Object_116,
      Object62: nodes.Object_118,
      Object63: nodes.Object_120,
      Object64: nodes.Object_122,
      Object65: nodes.Object_124,
      Object66: nodes.Object_126,
      Object67: nodes.Object_128,
      Object68: nodes.Object_130,
      Object69: nodes.Object_132,
      Object70: nodes.Object_134,
      Object71: nodes.Object_136,
      Object72: nodes.Object_138,
      Object73: nodes.Object_140,
      Object74: nodes.Object_142,
      Object75: nodes.Object_144,
      Object76: nodes.Object_146,
      Object77: nodes.Object_147,
    }),
    [nodes]
  );
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => (
        <context.Provider value={instances} children={children} />
      )}
    </Merged>
  );
}

export function Dance(props) {
  const { nodes, materials } = useGLTF("/assets/model/dance.glb");

  const instances = useContext(context);
  return (
    <group {...props} dispose={null}>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object />
        <instances.Object
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
        <instances.Object1 />
        <instances.Object1
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object2 />
        <instances.Object2
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object3 />
        <instances.Object3
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
        <instances.Object4 />
        <instances.Object4
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object5 />
        <instances.Object5
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
        <instances.Object6 />
        <instances.Object6
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object7 />
        <instances.Object7
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
        <instances.Object8 />
        <instances.Object8
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object9 />
        <instances.Object9
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
        <instances.Object10 />
        <instances.Object10
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object11 />
        <instances.Object11
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
        <instances.Object12 />
        <instances.Object12
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object13 />
        <instances.Object13
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
        <instances.Object14 />
        <instances.Object14
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object15 />
        <instances.Object15
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object16 />
        <instances.Object16
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object17 />
        <instances.Object17
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object18 />
        <instances.Object18
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object19 />
        <instances.Object19
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object20 />
        <instances.Object20
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object21 />
        <instances.Object21
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object22 />
        <instances.Object22
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object23 />
        <instances.Object23
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object24 />
        <instances.Object24
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object25 />
        <instances.Object25
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object26 />
        <instances.Object26
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object27 />
        <instances.Object27
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object28 />
        <instances.Object28
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object29 />
        <instances.Object29
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object30 />
        <instances.Object30
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object31 />
        <instances.Object31
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object32 />
        <instances.Object32
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object33 />
        <instances.Object33
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object34 />
        <instances.Object34
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object35 />
        <instances.Object35
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object36 />
        <instances.Object36
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object37 />
        <instances.Object37
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object38 />
        <instances.Object38
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object39 />
        <instances.Object39
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
        <instances.Object40 />
        <instances.Object40
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object41 />
        <instances.Object41
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
        <instances.Object42 />
        <instances.Object42
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object43 />
        <instances.Object43
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object44 />
        <instances.Object44
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object45 />
        <instances.Object45
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object46 />
        <instances.Object46
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object47 />
        <instances.Object47
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object48 />
        <instances.Object48
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object49 />
        <instances.Object49
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object50 />
        <instances.Object50
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object51 />
        <instances.Object51
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object52 />
        <instances.Object52
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object53 />
        <instances.Object53
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object54 />
        <instances.Object54
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object55 />
        <instances.Object55
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object56 />
        <instances.Object56
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object57 />
        <instances.Object57
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object58 />
        <instances.Object58
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object59 />
        <instances.Object59
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
        <instances.Object60 />
        <instances.Object60
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object61 />
        <instances.Object61
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object62 />
        <instances.Object62
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object63 />
        <instances.Object63
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object64 />
        <instances.Object64
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object65 />
        <instances.Object65
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object66 />
        <instances.Object66
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object67 />
        <instances.Object67
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object68 />
        <instances.Object68
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object69 />
        <instances.Object69
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object70 />
        <instances.Object70
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object71 />
        <instances.Object71
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object72 />
        <instances.Object72
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object73 />
        <instances.Object73
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object74 />
        <instances.Object74
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object75 />
        <instances.Object75
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-0.47, 0, 0.11]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object76 />
        <instances.Object76
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
        <instances.Object77 />
        <instances.Object77
          position={[0.83, 0.05, 0]}
          rotation={[0, 0, -Math.PI / 4]}
        />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object />
        <instances.Object1 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object2 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object3 />
        <instances.Object4 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object5 />
        <instances.Object6 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object7 />
        <instances.Object8 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object9 />
        <instances.Object10 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object11 />
        <instances.Object12 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object13 />
        <instances.Object14 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object15 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object16 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object17 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object18 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object19 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object20 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object21 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object22 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object23 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object24 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object25 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object26 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object27 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object28 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object29 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object30 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object31 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object32 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object33 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object34 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object35 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object36 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object37 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object38 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object39 />
        <instances.Object40 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object41 />
        <instances.Object42 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object43 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object44 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object45 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object46 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object47 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object48 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object49 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object50 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object51 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object52 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object53 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object54 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object55 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object56 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object57 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object58 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object59 />
        <instances.Object60 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object61 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object62 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object63 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object64 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object65 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object66 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object67 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object68 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object69 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object70 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object71 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object72 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object73 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object74 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object75 />
      </group>
      <group
        position={[-1.02, 0, 0.74]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[1, 1, 1.4]}
      >
        <instances.Object76 />
        <instances.Object77 />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials.material_5}
        position={[0, 0, 1.65]}
        scale={[1, 1.4, 1]}
      />
    </group>
  );
}

// useGLTF.preload("/dance.glb");
