/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Part4(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/assets/model/coin.glb");
  const { actions } = useAnimations(animations, group);
  // console.log(actions["Take 001"]);

  React.useEffect(() => {
    actions["Take 001"].play();
  }, []);

  return (
    <group ref={group} {...props} dispose={null} scale={0.025}>
      <group name="Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="8658c5a66acd4ddf843e5398106c1f80fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Cylinder001"
                  position={[-0.34, 28.88, -0.01]}
                  rotation={[Math.PI / 2, Math.PI / 2, 0]}
                >
                  <group name="Object_5" position={[0, 0, -4.78]}>
                    <mesh
                      name="Cylinder001_Material_#47_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Cylinder001_Material_#47_0"].geometry}
                      material={materials.Material_47}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

// useGLTF.preload("/coin.glb");
