/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Part2(props) {
  const { nodes, materials } = useGLTF("/assets/model/stadium2.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[-69.86, 0.93, 61.83]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Component#15_1"].geometry}
          material={materials.Ferozshahkotla015}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Component#15_2"].geometry}
          material={materials.Ferozshahkotla028}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Component#15_3"].geometry}
          material={materials["[Color_F05]"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Component#15_4"].geometry}
          material={materials.Ferozshahkotla027}
        />
      </group>
    </group>
  );
}
