/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Shop(props) {
  const { nodes, materials } = useGLTF("/assets/model/shop.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0.03, 8.33, 9.99]}
        rotation={[-1.57, 0, 0]}
        scale={0.42}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle009__0.geometry}
          material={materials.Rectangle009__0}
        />
      </group>
      <group
        position={[-0.01, 8.36, -84.28]}
        rotation={[-1.57, 0, 0]}
        scale={[1.38, 1.38, 0.32]}
      >
        <group position={[-3.83, -68.22, 285.01]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object002_PLASTIK_W_0.geometry}
            material={materials.PLASTIK_W}
          />
        </group>
      </group>
      <group
        position={[-0.01, 8.36, -84.28]}
        rotation={[-1.57, 0, 0]}
        scale={[1.38, 1.38, 0.32]}
      >
        <group position={[-3.83, -68.22, 285.01]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.LIGHT_light_0.geometry}
            material={materials.light}
          />
        </group>
      </group>
      <group
        position={[2.03, 8.36, -84.28]}
        rotation={[-1.57, 0, 0]}
        scale={1.38}
      >
        <group position={[-5.31, -68.22, 66.55]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.PLASTIK_W_PLASTIK_W_0.geometry}
            material={materials.PLASTIK_W}
          />
        </group>
      </group>
      <group
        position={[13.15, 8.36, -84.28]}
        rotation={[-1.57, 0, Math.PI]}
        scale={1.38}
      >
        <group position={[-44.5, 83.23, 66.55]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Object056_01_-_Default_0"].geometry}
            material={materials["01_-_Default"]}
          />
        </group>
      </group>
      <group
        position={[121.98, 8.36, -84.28]}
        rotation={[-1.57, 0, -Math.PI / 2]}
        scale={1.38}
      >
        <group position={[114.72, 0, 66.55]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["glass_01_-_Default_0"].geometry}
            material={materials["01_-_Default"]}
          />
        </group>
      </group>
      <group
        position={[-3.98, 8.36, -84.28]}
        rotation={[-1.57, 0, -Math.PI / 2]}
        scale={1.38}
      >
        <group position={[80.78, 54.42, 66.55]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.black_met__0.geometry}
            material={materials.Rectangle009__0}
          />
        </group>
      </group>
    </group>
  );
}

// useGLTF.preload("/shop.glb");
