/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF, Html } from "@react-three/drei";
import "../../App.css";

export default function Video(props) {
  //   console.log(props.src);
  const { nodes, materials } = useGLTF("/assets/model/screen.glb");

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.screen.geometry}
        material={materials["Material.001"]}
        // position={[-0.02, 0.84, -2.47]}
        // scale={0.26}
      >
        <Html
          className="content"
          // rotation-x={-Math.PI / 2}
          position={[0, 0, 0.225]}
          transform
          occlude
        >
          <div className="wrapper">
            <iframe
              width="1050"
              height="500"
              src={props.src}
              title="YouTube video player"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
            ></iframe>
          </div>
        </Html>
      </mesh>
    </group>
  );
}

// useGLTF.preload("/screen.glb");
